import "./globals.css";
import type { Metadata } from "next";
import { Dancing_Script, Inter, Manrope } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";

const dancing_script = Dancing_Script({
	subsets: ["latin"],
	variable: "--font-dancing_script",
});
const manRope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata: Metadata = {
	title: "Audiophile",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${manRope.variable} ${dancing_script.variable} text-white`}
			>
				<Header />
				<Toaster position="top-right" />
				<div className="max-w-[1128px] mx-auto px-5 py-12">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
